GET http://localhost:2410/products

#############


POST http://localhost:2410/contact
Content-Type: application/json

{
  "vorname": "Lukas",
  "nachname": "Semler",
  "emailAddr": "lukas.semler@gmail.com", 
  "betreff": "Das ist ein betreff", 
  "nachricht": "Das ist eine Nachricht", 
  "date": "2022-04-30"

}
#####


POST http://localhost:2410/register
Content-Type: application/json

{
  "vorname": "Lukas",
  "nachname": "Semler",
  "email": "lukas.semler@gmail.com",
  "strasse_hnr": "Venusweg 11",
  "stadt": "Wien",
  "plz": "1140",
  "password": "LukasPW"
}
